### PR TITLE
(feat) enforce black styling for PRs into master

### PR DESCRIPTION
**Pull request by vladdoster**
Saw you committed black formatting. This would enforce PRs to have proper formatting in order to be merged.

### CODE REVIEW

**Review by futzu — COMMENTED** [review]
```
ob3$ which black
/home/a/.local/bin/black
ob3$ conda
ksh: conda: not found
```
I like the idea, 
Do we need the conda stuff?

**Comment by futzu** [comment]
I'm not sure about this, let me think on it please.

**Comment by vladdoster** [comment]
Changed based on your feedback:

- Remove conda
- Test multiple versions of Python3
- Add Flake8 to catch obvious errors

**Comment by vladdoster** [comment]
@futzu any thoughts?

**Comment by futzu** [comment]
I'm just not familiar enough with it. 
Let me finish the encoding and I'll read up on it. 
I just need to understand how it works..

**Comment by vladdoster** [comment]
> I'm just not familiar enough with it.
> Let me finish the encoding and I'll read up on it.
> I just need to understand how it works..

Understand what? I removed Conda.

**Comment by futzu** [comment]
https://github.com/futzu/SCTE35-threefive/discussions/19

**Comment by futzu** [comment]
What happens if black isn't installed?
I don't know.  That's what I mean by understanding. 

We already have a Makefile. 
It's used to build and install threefive. 
I also have a target ```upload``` , 
that I use to push pip packages.
__make__ a ```commit```  target
so that ```make commit``` does something like this:
* ```git pull```
* ```black```
*  have it accept a list of files to commit
*  if no filenames are passed, then call ```git commit -a```
 * ```git push```

I don't want to add bells and whistles, 
that duplicate existing functionality 
and add dependencies. 

I need some help with the encoding work.
We need a TUI, like a dialog interface, 
like Anaconda uses for Red Hat installs,
to set SCTE35 Cue values

**Comment by vladdoster** [comment]
Can you send me a rough sketch of the desired TUI you are envisioning? I am familiar with Pythons curses package as well as the pydialog package.

**Comment by futzu** [comment]
https://github.com/futzu/SCTE35-threefive/issues/20

**Comment by futzu** [comment]
Can you still make the auto-black happen? 
You were right, this is a good idea. .

**Comment by futzu** [comment]
I merged it......

**Comment by futzu** [comment]
Can you make it enforced for all platforms? 

On Debian and OpenBSD, I have to call python3, 
python is 2.7.

**Pull request merged**
