### PR TITLE
Fix pcr parsing crash if pid is not in _pid_prgm

### PR DESCRIPTION
**Pull request by AudioDan**
Reverted a couple of lines of code in the pcr parsing to the way they were in 2.3.01.  This fixes parsing crashes on one sample video stream.

### CODE REVIEW

**Review by futzu — APPROVED** [review]

**Comment by futzu** [comment]
Dan, 
I took that out because I thought it was redundant. 

In `_parse` I check that its a pcr pid
```
        if pid in self._pids["pcr"]:
            return self._parse_pcr(pkt, pid)
```
If its a pcr pid , then it should have been added to 
_pid_prgm In `_parse_program_streams`

```
            self._pid_prgm[pid] = program_number
```

Is your pcr pid not in a program stream or am I just missing something?

**Comment by futzu** [comment]
Do you have a PMT split over multiple packets?

**Comment by AudioDan** [comment]
Would a tsduck/tsanalyze output help answer your questions?  See the attached text file.  I am not sure but I think the problematic pid might 8190 or 8191.
[tsduck_tsanalyze_output.txt](https://github.com/futzu/scte35-threefive/files/7455461/tsduck_tsanalyze_output.txt)

**Comment by futzu** [comment]
8190 is your pcr pid.

Could you show me the output of  Stream.show()

```
import sys
from threefive import Stream 


def do():
    args= sys.argv[1:]
    for arg in args:
        Stream(arg).show()

if __name__ == "__main__":
    do()
```

**Comment by AudioDan** [comment]
Program: 1

    Service: cod30.enc.phx59:Redacted
    Provider: Redacted

    Stream:  pid:308[0x134]     type:0x1b
    Stream:  pid:256[0x100]     type:0x3
    Stream:  pid:257[0x101]     type:0x3
    Stream:  pid:258[0x102]     type:0x86

**Comment by futzu** [comment]
Scratch that.

**Comment by futzu** [comment]
In that stream.py, I add the pcr_pid  to _pid_prgm when the pcr_pid is discovered.

```python
    def _program_map_table(self, payload, pid):
        """
        parse program maps for streams
        """
        payload = self._chk_partial(payload, pid)
        payload = self._split_by_idx(payload, b"\x02")
        if not payload:
            return
        sectioninfolen = self._parse_length(payload[1], payload[2])
        if sectioninfolen + 3 > len(payload):
            self._partial[pid] = payload
            return
        program_number = self._parse_program(payload[3], payload[4])
        if self.the_program and (program_number != self.the_program):
            return
        pcr_pid = self._parse_pid(payload[8], payload[9])
        if program_number not in self._prgm:
            pinfo = ProgramInfo()
            pinfo.pid = pid
            self._prgm[program_number] = pinfo
        self._pids["pcr"].add(pcr_pid)


        self._pid_prgm[pid] = program_number                #  <--- Adding pcr pid here



        proginfolen = self._parse_length(payload[10], payload[11])
        idx = 12
        idx += proginfolen
        si_len = sectioninfolen - 9
        si_len -= proginfolen
        self._parse_program_streams(si_len, payload, idx, program_number)
```

**Comment by AudioDan** [comment]
If I use your stream show script after applying the new stream.py file you sent I get:
Traceback (most recent call last):
  File "E:\ClientWork\2021-10-21\stream_show.py", line 11, in <module>
    do()
  File "E:\ClientWork\2021-10-21\stream_show.py", line 8, in do
    Stream(arg).show()
  File "C:\Python39\lib\site-packages\threefive-2.3.5-py3.9.egg\threefive\stream.py", line 208, in show
  File "C:\Python39\lib\site-packages\threefive-2.3.5-py3.9.egg\threefive\stream.py", line 126, in decode
  File "C:\Python39\lib\site-packages\threefive-2.3.5-py3.9.egg\threefive\stream.py", line 328, in _parse
  File "C:\Python39\lib\site-packages\threefive-2.3.5-py3.9.egg\threefive\stream.py", line 302, in _parse_pcr
KeyError: 8190

**Comment by futzu** [comment]
Damn it , I did that incorrectly.

**Comment by futzu** [comment]
Hold on ......

**Comment by futzu** [comment]
Last test , I swear....
[stream.py.2.txt](https://github.com/futzu/scte35-threefive/files/7455943/stream.py.2.txt)

**Comment by AudioDan** [comment]
Don't sweat it.  I don't mind banging on this to get it a good as we can.  Hang on.

**Comment by AudioDan** [comment]
First test looks like it works.  Should I put it into my vm and use tsplay to push it as a stream and see how that goes?

**Comment by futzu** [comment]
Yes please

**Comment by AudioDan** [comment]
Give me a few.  This might take a bit because testing is real time streams plus I need to get it set up.

**Comment by AudioDan** [comment]
I am going to do this using the file you sent on top of master as opposed to my branch of 2.3.05 unless you think there is anything in the most recent changes of master that are questionable.  I am building and updating the vm now and then will get some streams going.

**Comment by AudioDan** [comment]
This is looking good so far.  I have about 3 hours worth of test files I am going to play through, but the 24 min file that was causing problems was crashing immediately on playback start and now it seems to be playing through fine and we have logged several successful json breaks.  I will run though the rest of the files as well this evening but I think this is good.

**Comment by futzu** [comment]
cool man, thank you.

**Comment by AudioDan** [comment]
Tests are looking good on my end.  We will probably be trying to put it up against the live streams late tomorrow, but since the files we have been testing against are just captures of portions of those "same" streams, I think we will be good.  Should we stick with master and are you going to be committing the change, or would it be better for me to just apply this patch against the 2.3.05 branch I made in my fork.

**Comment by futzu** [comment]
The changes are already up.
I'll do a release right now,  this is significant.

**Comment by futzu** [comment]
https://pypi.org/project/threefive/2.3.7/

**Pull request merged**
